name: AERO ingestion example

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  ingestion:
    strategy:
      matrix:
        flowid: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    runs-on: ubuntu-latest

    env:
      GLOBUS_COMPUTE_CLIENT_ID: ${{ secrets.GLOBUS_COMPUTE_CLIENT_ID }}
      GLOBUS_COMPUTE_CLIENT_SECRET: ${{ secrets.GLOBUS_COMPUTE_CLIENT_SECRET }}
      ENDPOINT_UUID: 9c0edc45-d6e3-461a-8664-5bbbe6f4af23 #a48932e3-3a20-454b-9c1e-3aff354f3551 #e05fba2c-5959-42db-a56d-ca7ba7a24818
      REGISTER_FUNCTION_UUID: e70dc953-90e3-4c13-be43-9e9b9e350e34 # 97ad6b1c-0326-4799-b13e-7a8644e60526
      DOWNLOAD_FUNCTION_UUID: e70dc953-90e3-4c13-be43-9e9b9e350e34 # 5ca3af28-d262-4429-b010-c89ad2f528e2
      CUSTOM_FUNCTION_UUID: e70dc953-90e3-4c13-be43-9e9b9e350e34 # a5f47c46-c6e7-4058-a520-c8ea091f0535 #b77f10f9-8d32-410e-8b2c-74b9ae00ad34 # a272fa1b-3dc4-471b-b69c-2ce7ae195bf2
      COMMIT_FUNCTION_UUID: e70dc953-90e3-4c13-be43-9e9b9e350e34 # 7cd724b1-64fd-461d-b946-ee0e26dc9134

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install Globus Compute
      run: pip install globus-compute-sdk
    - name: Register flow with AERO
      run: |
        echo "Step Started"
        python action_inputs/execute_function.py register >> $GITHUB_OUTPUT
        echo "Step Completed"
      id: register
    - name: Run download
      run: |
        echo "Step Started ${{ steps.register.outputs.result }}"
        python action_inputs/execute_function.py download "${{ steps.register.outputs.result }}" >> $GITHUB_OUTPUT
        echo "Step Completed"
      id: download
    - name: Run custom-user-function
      run: |
        echo "Step Started"
        python action_inputs/execute_function.py custom "${{ steps.download.outputs.result }}"  >> $GITHUB_OUTPUT
        echo "Step Completed"
      id: custom-uf
    - name: Run database-commit
      run: |
        echo "Step Started"
        python action_inputs/execute_function.py commit "${{ steps.custom-uf.outputs.result }}"
        echo "Step Completed"
      id: db-commit
