name: AERO ingestion example

on:
  schedule:
    - cron: "0 0 * * *" 
  push:
    
jobs:
  ingestion:
    strategy:
      matrix:
        flowid: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] #, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    runs-on: ubuntu-latest

    env:
      GLOBUS_COMPUTE_CLIENT_ID: ${{ secrets.GLOBUS_COMPUTE_CLIENT_ID }}
      GLOBUS_COMPUTE_CLIENT_SECRET: ${{ secrets.GLOBUS_COMPUTE_CLIENT_SECRET }}
      ENDPOINT_UUID: e05fba2c-5959-42db-a56d-ca7ba7a24818
      DOWNLOAD_FUNCTION_UUID: 5ca3af28-d262-4429-b010-c89ad2f528e2
      CUSTOM_FUNCTION_UUID: a272fa1b-3dc4-471b-b69c-2ce7ae195bf2
      COMMIT_FUNCTION_UUID: 7cd724b1-64fd-461d-b946-ee0e26dc9134 
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install Globus Compute
      run: pip install globus-compute-sdk
    - name: Run download
      run: python action_inputs/execute_function.py ${{ env.DOWNLOAD_FUNCTION_UUID }} >> $GITHUB_OUTPUT
      id: download
    - name: Run custom-user-function
      run: python action_inputs/execute_function.py ${{ env.CUSTOM_FUNCTION_UUID }} "${{ steps.download.outputs.result }}" >> $GITHUB_OUTPUT
      id: custom-uf
    - name: Run database-commit
      run: python action_inputs/execute_function.py ${{ env.COMMIT_FUNCTION_UUID }} "${{ steps.custom-uf.outputs.result }}"
      id: db-commit

    
